#!/bin/bash

# network-hardening.sh - Network configuration and protocol hardening
# Based on CIS Ubuntu Linux 22.04 LTS Benchmark v3.0.0
# Controls: 3.1 (IP forwarding), 3.2 (ICMP), 3.3 (TCP/IP stack), 3.4 (TCP wrappers), 3.5 (firewall)

# Determine script directory and repository root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Load utility functions
source "$REPO_ROOT/scripts/utils/logger.sh"
source "$REPO_ROOT/scripts/utils/validation.sh" 2>/dev/null || true

# Configuration
DRY_RUN=false
CHANGES_MADE=0
CHANGES_PLANNED=0
SYSCTL_CONF="/etc/sysctl.d/99-cis-network-hardening.conf"

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --dry-run) DRY_RUN=true ;;
        -h|--help)
            echo "Usage: $0 [--dry-run]"
            echo "  --dry-run    Show what changes would be made without applying them"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
    shift
done

# Check if running as root
if [ "$EUID" -ne 0 ] && [ "$DRY_RUN" = false ]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

log_info "Starting network hardening..."

# Define all sysctl parameters to apply
declare -A SYSCTL_PARAMS

# CIS 3.1 - Disable network forwarding
SYSCTL_PARAMS["net.ipv4.ip_forward"]="0"
SYSCTL_PARAMS["net.ipv6.conf.all.forwarding"]="0"

# CIS 3.2 - Disable packet redirect sending
SYSCTL_PARAMS["net.ipv4.conf.all.send_redirects"]="0"
SYSCTL_PARAMS["net.ipv4.conf.default.send_redirects"]="0"
SYSCTL_PARAMS["net.ipv4.conf.all.accept_redirects"]="0"
SYSCTL_PARAMS["net.ipv4.conf.default.accept_redirects"]="0"
SYSCTL_PARAMS["net.ipv4.conf.all.secure_redirects"]="0"
SYSCTL_PARAMS["net.ipv4.conf.default.secure_redirects"]="0"
SYSCTL_PARAMS["net.ipv6.conf.all.accept_redirects"]="0"
SYSCTL_PARAMS["net.ipv6.conf.default.accept_redirects"]="0"

# CIS 3.3 - Network parameters
SYSCTL_PARAMS["net.ipv4.conf.all.accept_source_route"]="0"
SYSCTL_PARAMS["net.ipv4.conf.default.accept_source_route"]="0"
SYSCTL_PARAMS["net.ipv6.conf.all.accept_source_route"]="0"
SYSCTL_PARAMS["net.ipv6.conf.default.accept_source_route"]="0"
SYSCTL_PARAMS["net.ipv4.icmp_echo_ignore_broadcasts"]="1"
SYSCTL_PARAMS["net.ipv4.icmp_ignore_bogus_error_responses"]="1"
SYSCTL_PARAMS["net.ipv4.conf.all.rp_filter"]="1"
SYSCTL_PARAMS["net.ipv4.conf.default.rp_filter"]="1"
SYSCTL_PARAMS["net.ipv4.tcp_syncookies"]="1"
SYSCTL_PARAMS["net.ipv6.conf.all.accept_ra"]="0"
SYSCTL_PARAMS["net.ipv6.conf.default.accept_ra"]="0"
SYSCTL_PARAMS["net.ipv4.conf.all.log_martians"]="1"
SYSCTL_PARAMS["net.ipv4.conf.default.log_martians"]="1"

# Additional TCP hardening
SYSCTL_PARAMS["net.ipv4.tcp_max_syn_backlog"]="2048"
SYSCTL_PARAMS["net.ipv4.tcp_synack_retries"]="2"
SYSCTL_PARAMS["net.ipv4.tcp_syn_retries"]="5"
SYSCTL_PARAMS["net.ipv4.tcp_timestamps"]="1"

if [ "$DRY_RUN" = true ]; then
    log_info "[DRY RUN MODE] - No changes will be made"
    log_info ""
    log_info "The following settings would be applied to $SYSCTL_CONF:"
    log_info ""
    
    for param in "${!SYSCTL_PARAMS[@]}"; do
        value="${SYSCTL_PARAMS[$param]}"
        current=$(sysctl -n "$param" 2>/dev/null || echo "N/A")
        if [ "$current" = "$value" ]; then
            log_info "  $param = $value (already set)"
        else
            log_info "  $param = $value (current: $current) [WOULD CHANGE]"
            ((CHANGES_PLANNED++))
        fi
    done
    
    log_info ""
    log_info "Dry run completed: ${CHANGES_PLANNED} changes would be made"
    log_warning "Run without --dry-run to apply changes"
    exit 0
fi

# Create the sysctl configuration file
log_info "Creating sysctl configuration file: $SYSCTL_CONF"

# Backup existing file if present
if [ -f "$SYSCTL_CONF" ]; then
    cp "$SYSCTL_CONF" "${SYSCTL_CONF}.backup.$(date +%Y%m%d_%H%M%S)"
    log_info "Backed up existing configuration"
fi

# Write the configuration file directly
cat > "$SYSCTL_CONF" << 'HEADER'
# CIS Ubuntu Linux 22.04 LTS Benchmark - Network Hardening
# Generated by network-hardening.sh
# Do not edit manually - changes will be overwritten

#####################################################################
# CIS 3.1 - Network Forwarding
#####################################################################
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0

#####################################################################
# CIS 3.2 - Packet Redirect Settings
#####################################################################
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

#####################################################################
# CIS 3.3 - Network Parameters
#####################################################################
# Source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# ICMP settings
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Reverse path filtering
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# SYN flood protection
net.ipv4.tcp_syncookies = 1

# IPv6 router advertisements
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0

# Log suspicious packets (martians)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

#####################################################################
# Additional TCP Hardening
#####################################################################
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5
net.ipv4.tcp_timestamps = 1
HEADER

# Verify the file was written
if [ ! -f "$SYSCTL_CONF" ]; then
    log_error "Failed to create $SYSCTL_CONF"
    exit 1
fi

# Check file has content
file_size=$(stat -c%s "$SYSCTL_CONF" 2>/dev/null || echo "0")
if [ "$file_size" -lt 100 ]; then
    log_error "Configuration file appears to be empty or too small"
    exit 1
fi

log_success "Configuration file created successfully ($file_size bytes)"

# Display file contents for verification
log_info "Configuration file contents:"
cat "$SYSCTL_CONF"

# Apply the settings immediately
log_info ""
log_info "Applying sysctl settings..."

# Apply each setting individually and count successes
for param in "${!SYSCTL_PARAMS[@]}"; do
    value="${SYSCTL_PARAMS[$param]}"
    if sysctl -w "${param}=${value}" >/dev/null 2>&1; then
        ((CHANGES_MADE++))
    else
        log_warning "Could not apply $param (may not be supported)"
    fi
done

# Also apply from the config file to ensure everything is loaded
log_info "Loading configuration from $SYSCTL_CONF..."
if sysctl -p "$SYSCTL_CONF" 2>&1; then
    log_success "Applied settings from configuration file"
else
    log_warning "Some settings may not have been applied (check for errors above)"
fi

# Reload sysctl service to ensure persistence
if command -v systemctl &>/dev/null; then
    log_info "Restarting systemd-sysctl service..."
    systemctl restart systemd-sysctl.service 2>/dev/null && log_success "Service restarted" || log_warning "Could not restart service"
fi

# Verify a few key settings
log_info ""
log_info "Verifying applied settings:"
log_info "  net.ipv4.ip_forward = $(sysctl -n net.ipv4.ip_forward 2>/dev/null || echo 'error')"
log_info "  net.ipv4.tcp_syncookies = $(sysctl -n net.ipv4.tcp_syncookies 2>/dev/null || echo 'error')"
log_info "  net.ipv4.conf.all.accept_redirects = $(sysctl -n net.ipv4.conf.all.accept_redirects 2>/dev/null || echo 'error')"
log_info "  net.ipv4.conf.all.log_martians = $(sysctl -n net.ipv4.conf.all.log_martians 2>/dev/null || echo 'error')"

# Summary
log_info ""
log_info "═══════════════════════════════════════════════════════════"
log_info "  NETWORK HARDENING SUMMARY"
log_info "═══════════════════════════════════════════════════════════"
log_success "Network hardening completed: ${CHANGES_MADE} settings applied"
log_info ""
log_info "Configuration saved to: $SYSCTL_CONF"
log_info ""
log_info "CIS Controls Applied:"
log_info "  • 3.1.x - IP forwarding disabled"
log_info "  • 3.2.x - ICMP redirects disabled"
log_info "  • 3.3.x - TCP/IP stack hardening"
log_info ""
log_info "Settings are persistent across reboots."
log_warning "Verify network connectivity after applying changes"
log_info "═══════════════════════════════════════════════════════════"

exit 0
